### ISSUE TITLE
验证IP变动，请求更新

### ISSUE THREAD

**Issue by splendidmata** [phguo/Auto-nuaa.portal#1]
现验证页ip：222.192.72.253

**Comment by phguo** [comment]
江宁校区的 ip 到目前为止依然是 211.65.106.6，不太清楚其他两校区 ip 是什么。

但是江宁校区 wlan_ac_name 变为 nuaa_jjl_me60_2，Alfred workflow 中这一参数值为 JiangNing_ME60，Apple shortcuts 缺少这一参数，导致登录失败。请验证。

```python
def login(username, password, login_ip='211.65.106.6'):
    login_parameters = {
        "c": "Portal",
        "a": "login",
        "callback": "dr1003",
        "login_method": "1",
        "user_account": ",0," + username,
        "user_password": str(password),
        "wlan_user_ip": get_ip(),
        "wlan_user_ipv6": "",
        "wlan_user_mac": "000000000000",
        "wlan_ac_ip": "",
        # "wlan_ac_name": "JiangNing_ME60",
        "wlan_ac_name": "nuaa_jjl_me60_2",
        "jsVersion": "3.3.2",
        "v": "5780",
    }
    login_url = "http://{}:801/eportal/".format(login_ip)
    login_request = requests.get(login_url, params=login_parameters)
    login_text_content = login_request.text
    try:
        login_text_content = login_text_content.replace("dr1003(", '').replace(')', '')
    except:
        pass
```

**Comment by phguo** [comment]
> 江宁校区的 ip 到目前为止依然是 211.65.106.6，不太清楚其他两校区 ip 是什么。
> 
> 但是江宁校区 wlan_ac_name 变为 nuaa_jjl_me60_2，Alfred workflow 中这一参数值为 JiangNing_ME60，Apple shortcuts 缺少这一参数，导致登录失败。请验证。
> 
> ```python
> def login(username, password, login_ip='211.65.106.6'):
>     login_parameters = {
>         "c": "Portal",
>         "a": "login",
>         "callback": "dr1003",
>         "login_method": "1",
>         "user_account": ",0," + username,
>         "user_password": str(password),
>         "wlan_user_ip": get_ip(),
>         "wlan_user_ipv6": "",
>         "wlan_user_mac": "000000000000",
>         "wlan_ac_ip": "",
>         # "wlan_ac_name": "JiangNing_ME60",
>         "wlan_ac_name": "nuaa_jjl_me60_2",
>         "jsVersion": "3.3.2",
>         "v": "5780",
>     }
>     login_url = "http://{}:801/eportal/".format(login_ip)
>     login_request = requests.get(login_url, params=login_parameters)
>     login_text_content = login_request.text
>     try:
>         login_text_content = login_text_content.replace("dr1003(", '').replace(')', '')
>     except:
>         pass
> ```
登录失败的原因是`get_ip`获取 ip 错误。

**Comment by phguo** [comment]
已增加自定义 ip 的选项（[v1.1](https://github.com/phguo/Auto-nuaa.portal/releases/tag/v1.1)）。

**Comment by phguo** [comment]
> 已增加自定义 ip 的选项（[v1.1](https://github.com/phguo/Auto-nuaa.portal/releases/tag/v1.1)）。

可在`config.py`或 Alfred workflow environment variables 中修改。当二者共存时前者优先级更高。
